### ISSUE TITLE
Why use "super" as temporary variable?

### ISSUE THREAD

**Issue by mmclkv** [rmcgibbo/npcuda-example#2]
Hi Robert, very appreciated for sharing this tricky yet effective example code! But there is just one thing that I can't figure out. In cython/setup.py, line 88-89, it looks like this:

`default_compiler_so = self.compiler_so`
`super = self._compile` 

Can you explain the reason why you use "super" as temporary variable to store the function _compile? Thanks a lot!

**Comment by rmcgibbo** [comment]
I'm overriding a method on an object instance, and using super to refer to initial version of the method that's being shadowed.

**Comment by mmclkv** [comment]
I think I get your intention, thanks! Just haven't seen any usage of super like this :)
