### ISSUE TITLE
PIP install fails 

### ISSUE THREAD

**Issue by devmessias** [rmcgibbo/npcuda-example#7]
```
python setup.py sdist && cd dist && ls && pip install gpuadder-0.1.tar.gz
```

```
Building wheels for collected packages: gpuadder
  Building wheel for gpuadder (setup.py) ... error
  ERROR: Failed building wheel for gpuadder
```
Should it be possible to create a pip package from your source code?

**Comment by rmcgibbo** [comment]
this package essentially hasn't been touched in years, so i think it's just on a best-effort basis. sorry.

**Comment by devmessias** [comment]
Ah!  I see now . It's just a missing MANIFEST.in

Thanks for your repo!

**Comment by rmcgibbo** [comment]
feel free to add that to the repo if you like
